<?php
namespace Sdk\Common\Adapter;

trait CommonMapErrorsTrait
{
    public function commonMapErrors()
    {
        return [
            10 => RESOURCE_NOT_EXIST,
            100 => PARAMETER_IS_UNIQUE,
            101 => PARAMETER_FORMAT_INCORRECT,
            102 => PARAMETER_IS_EMPTY,
            103 => RESOURCE_STATUS_ON_SHELF,
            104 => RESOURCE_STATUS_OFF_STOCK,
            105 => RESOURCE_STATUS_NOT_PENDING,
            106 => RESOURCE_STATUS_NOT_REJECT,
            107 => RESOURCE_STATUS_NOT_ON_SHELF,
            108 => RESOURCE_STATUS_NOT_NORMAL,
            109 => RESOURCE_STATUS_DISABLED,
            110 => RESOURCE_STATUS_ENABLED,
            201 => IMAGE_FORMAT_ERROR,
            202 => ATTACHMENT_FORMAT_ERROR,
            203 => REAL_NAME_FORMAT_ERROR,
            204 => CELLPHONE_FORMAT_ERROR,
            205 => PRICE_FORMAT_ERROR,
            206 => CARDID_FORMAT_ERROR,
            207 => DATE_FORMAT_ERROR,
            208 => NAME_FORMAT_ERROR,
            209 => ADDRESS_FORMAT_ERROR,
            210 => URL_FORMAT_ERROR,
            211 => TITLE_FORMAT_ERROR,
            212 => DESCRIPTION_FORMAT_ERROR,
            213 => REJECT_REASON_FORMAT_ERROR,
            214 => DETAIL_FORMAT_ERROR,
            1001 => GENDER_TYPE_NOT_EXIST,
            1002 => PASSWORD_FORMAT_ERROR,
            1003 => OLD_PASSWORD_INCORRECT,
            1004 => PASSWORD_INCORRECT,
            2001 => NICK_NAME_FORMAT_ERROR,
            2002 => BRIEF_INTRODUCTION_FORMAT_ERROR,
            4001 => UNIFIED_SOCIAL_CREDIT_CODE_FORMAT_ERROR,
            6001 => APPLICABLE_OBJECT_NOT_EXIST,
            6002 => APPLICABLE_INDUSTRIES_NOT_EXIST,
            6003 => LEVEL_NOT_EXIST,
            6004 => CLASSIFY_NOT_EXIST,
            6005 => ADMISSIBLE_ADDRESS_FORMAT_ERROR,
            8001 => DISPATCH_DEPARTMENT_NAME_FORMAT_ERROR,
            8002 => DISPATCH_DEPARTMENT_REMARK_FORMAT_ERROR,
            9001 => LABEL_NAME_FORMAT_ERROR,
            9002 => LABEL_CATEGORY_NOT_EXIST,
            9003 => LABEL_REMARK_FORMAT_ERROR,
            10001 => SERVICE_CATEGORY_NAME_FORMAT_ERROR,
            10002 => SERVICE_CATEGORY_QUALIFICATION_NAME_FORMAT_ERROR,
            10003 => SERVICE_CATEGORY_IS_QUALIFICATION_NOT_EXIST,
            12001 => SERVICE_REQUIREMENT_TITLE_FORMAT_ERROR,
            12002 => MIN_PRICE_CAN_NOT_THAN_MAX_PRICE,
            13001 => SERVICE_TITLE_FORMAT_ERROR,
            13002 => SERVICE_OBJECT_NOT_EXIST,
            13003 => SERVICE_PRICE_FORMAT_ERROR,
            13004 => SERVICE_CONTRACT_FORMAT_ERROR,
            13005 => ENTERPRISE_NOT_AUTHENTICATION_SERVICE_CATEGORY
        ];
    }
}
