<?php

return array(
    CSRF_VERIFY_FAILURE=>
        array(
            'id'=>CSRF_VERIFY_FAILURE,
            'link'=>'',
            'status'=>403,
            'code'=>'CSRF_VERIFY_FAILURE',
            'title'=>'csrf验证失效',
            'detail'=>'csrf验证失效,请刷新页面',
            'source'=>array(
            ),
            'meta'=>array()
        ),
    AFS_VERIFY_FAILURE=>
        array(
            'id'=>AFS_VERIFY_FAILURE,
            'link'=>'',
            'status'=>403,
            'code'=>'AFS_VERIFY_FAILURE',
            'title'=>'滑动验证失效',
            'detail'=>'滑动验证失效,请刷新页面',
            'source'=>array(
            ),
            'meta'=>array()
        ),
    NEED_SIGNIN=>
        array(
            'id'=>NEED_SIGNIN,
            'link'=>'',
            'status'=>403,
            'code'=>'NEED_SIGNIN',
            'title'=>'用户未登录',
            'detail'=>'用户未登录',
            'source'=>array(
            ),
            'meta'=>array()
        ),
    SMS_SEND_TOO_QUICK=>
        array(
            'id'=>SMS_SEND_TOO_QUICK,
            'link'=>'',
            'status'=>403,
            'code'=>'SMS_SEND_TOO_QUICK',
            'title'=>'短信发送太频繁',
            'detail'=>'短信发送太频繁',
            'source'=>array(
            ),
            'meta'=>array()
        ),
    PARAMETER_IS_UNIQUE=>
        array(
            'id'=>PARAMETER_IS_UNIQUE,
            'link'=>'',
            'status'=>409,
            'code'=>'PARAMETER_IS_UNIQUE',
            'title'=>'数据重复',
            'detail'=>'表述传输了一个已经存在的数据,但是该数据不能重复',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PARAMETER_FORMAT_INCORRECT=>
        array(
            'id'=>PARAMETER_FORMAT_INCORRECT,
            'link'=>'',
            'status'=>403,
            'code'=>'PARAMETER_FORMAT_INCORRECT',
            'title'=>'数据格式不正确',
            'detail'=>'表述传输了一个格式不正确的字段',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PARAMETER_IS_EMPTY=>
        array(
            'id'=>PARAMETER_IS_EMPTY,
            'link'=>'',
            'status'=>403,
            'code'=>'PARAMETER_IS_EMPTY',
            'title'=>'数据不能为空',
            'detail'=>'表述传输了一个空数据,但是该数据不能为空',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_ON_SHELF=>
        array(
            'id'=>RESOURCE_STATUS_ON_SHELF,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_ON_SHELF',
            'title'=>'状态已上架',
            'detail'=>'该资源状态已上架',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_OFF_STOCK=>
        array(
            'id'=>RESOURCE_STATUS_OFF_STOCK,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_OFF_STOCK',
            'title'=>'状态已下架',
            'detail'=>'该资源状态已下架',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_PENDING=>
        array(
            'id'=>RESOURCE_STATUS_NOT_PENDING,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_PENDING',
            'title'=>'审核状态非待审核',
            'detail'=>'该资源已经审核',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_REJECT=>
        array(
            'id'=>RESOURCE_STATUS_NOT_REJECT,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_REJECT',
            'title'=>'审核状态非已拒绝',
            'detail'=>'该资源非已拒绝',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_ON_SHELF=>
        array(
            'id'=>RESOURCE_STATUS_NOT_ON_SHELF,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_ON_SHELF',
            'title'=>'状态非上架状态',
            'detail'=>'该资源非已上架',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_NOT_NORMAL=>
        array(
            'id'=>RESOURCE_STATUS_NOT_NORMAL,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_NOT_NORMAL',
            'title'=>'状态非正常状态',
            'detail'=>'该资源非正常状态',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_DISABLED=>
        array(
            'id'=>RESOURCE_STATUS_DISABLED,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_DISABLED',
            'title'=>'状态已禁用',
            'detail'=>'表述该资源状态已禁用',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    RESOURCE_STATUS_ENABLED=>
        array(
            'id'=>RESOURCE_STATUS_ENABLED,
            'link'=>'',
            'status'=>403,
            'code'=>'RESOURCE_STATUS_ENABLED',
            'title'=>'状态已启用',
            'detail'=>'表述该资源状态已启用',
            'source'=>array(
                'pointer'=>'status'
            ),
            'meta'=>array()
        ),
    IMAGE_FORMAT_ERROR=>
        array(
            'id'=>IMAGE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'IMAGE_FORMAT_ERROR',
            'title'=>'图片格式错误',
            'detail'=>'照片格式不正确，请重新上传，正确格式为jpg,png,jpeg',
            'source'=>array(
                'pointer'=>'image'
            ),
            'meta'=>array()
        ),
    ATTACHMENT_FORMAT_ERROR=>
        array(
            'id'=>ATTACHMENT_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'ATTACHMENT_FORMAT_ERROR',
            'title'=>'附件格式错误',
            'detail'=>'附件格式错误，附件格式为zip, doc, docx，xls, xlsx，ppt',
            'source'=>array(
                'pointer'=>'attachments'
            ),
            'meta'=>array()
        ),
    REAL_NAME_FORMAT_ERROR=>
        array(
            'id'=>REAL_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'REAL_NAME_FORMAT_ERROR',
            'title'=>'姓名格式错误',
            'detail'=>'请输入正确的姓名',
            'source'=>array(
                'pointer'=>'attachments'
            ),
            'meta'=>array()
        ),
    CELLPHONE_FORMAT_ERROR=>
        array(
            'id'=>CELLPHONE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CELLPHONE_FORMAT_ERROR',
            'title'=>'手机号格式错误',
            'detail'=>'请填写正确的手机号码',
            'source'=>array(
                'pointer'=>'attachments'
            ),
            'meta'=>array()
       ),
    PRICE_FORMAT_ERROR=>
        array(
            'id'=>PRICE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'PRICE_FORMAT_ERROR',
            'title'=>'价格格式不正确',
            'detail'=>'价格格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    CARDID_FORMAT_ERROR=>
        array(
            'id'=>CARDID_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CARDID_FORMAT_ERROR',
            'title'=>'身份号格式不正确',
            'detail'=>'请填写正确的身份证号',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    DATE_FORMAT_ERROR=>
        array(
            'id'=>DATE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DATE_FORMAT_ERROR',
            'title'=>'日期格式不正确',
            'detail'=>'日期格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    NAME_FORMAT_ERROR=>
        array(
            'id'=>NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'NAME_FORMAT_ERROR',
            'title'=>'名称格式不正确',
            'detail'=>'名称格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    ADDRESS_FORMAT_ERROR=>
        array(
            'id'=>ADDRESS_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'ADDRESS_FORMAT_ERROR',
            'title'=>'详细地址格式不正确',
            'detail'=>'详细地址格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    URL_FORMAT_ERROR=>
        array(
            'id'=>URL_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'URL_FORMAT_ERROR',
            'title'=>'url格式不正确',
            'detail'=>'url格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    TITLE_FORMAT_ERROR=>
        array(
            'id'=>TITLE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'TITLE_FORMAT_ERROR',
            'title'=>'标题格式不正确',
            'detail'=>'标题格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    DESCRIPTION_FORMAT_ERROR=>
        array(
            'id'=>DESCRIPTION_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DESCRIPTION_FORMAT_ERROR',
            'title'=>'描述格式不正确',
            'detail'=>'描述格式错误',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    REJECT_REASON_FORMAT_ERROR=>
        array(
            'id'=>REJECT_REASON_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'REJECT_REASON_FORMAT_ERROR',
            'title'=>'驳回原因格式不正确',
            'detail'=>'驳回原因格式不正确.',
            'source'=>array(
                'pointer'=>'rejectReason'
            ),
            'meta'=>array()
        ),
    DETAIL_FORMAT_ERROR=>
        array(
            'id'=>DETAIL_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DETAIL_FORMAT_ERROR',
            'title'=>'详情格式不正确',
            'detail'=>'详情格式不正确.',
            'source'=>array(
                'pointer'=>'detail'
            ),
            'meta'=>array()
        ),
    GENDER_TYPE_NOT_EXIST=>
        array(
            'id'=>GENDER_TYPE_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'GENDER_TYPE_NOT_EXIST',
            'title'=>'性别类型不存在',
            'detail'=>'性别类型不存在',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PASSWORD_FORMAT_ERROR=>
        array(
            'id'=>PASSWORD_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,PASSWORD_FORMAT_ERROR,
            'code'=>'PASSWORD_FORMAT_ERROR',
            'title'=>'密码格式不正确',
            'detail'=>'密码长度为6-18位，必须包含数字和字母',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    OLD_PASSWORD_INCORRECT=>
        array(
            'id'=>OLD_PASSWORD_INCORRECT,
            'link'=>'',
            'status'=>403,
            'code'=>'OLD_PASSWORD_INCORRECT',
            'title'=>'旧密码不正确',
            'detail'=>'旧密码不正确',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    PASSWORD_INCORRECT=>
        array(
            'id'=>PASSWORD_INCORRECT,
            'link'=>'',
            'status'=>403,
            'code'=>'PASSWORD_INCORRECT',
            'title'=>'账号密码不匹配',
            'detail'=>'账号和密码不匹配，请检查您的输入',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    CELLPHONE_EXIST=>
        array(
            'id'=>CELLPHONE_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'CELLPHONE_EXIST',
            'title'=>'手机号已存在',
            'detail'=>'该手机号已存在，请重新输入',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    CELLPHONE_NOT_EXIST=>
        array(
            'id'=>CELLPHONE_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'CELLPHONE_NOT_EXIST',
            'title'=>'账号不存在',
            'detail'=>'账号不存在，请检查您的输入',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    CAPTCHA_ERROR=>
        array(
            'id'=>CAPTCHA_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CAPTCHA_ERROR',
            'title'=>'验证码不正确',
            'detail'=>'验证码有误，请重新填写',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    INCONSISTENT_PASSWORD=>
        array(
            'id'=>INCONSISTENT_PASSWORD,
            'link'=>'',
            'status'=>403,
            'code'=>'INCONSISTENT_PASSWORD',
            'title'=>'确认密码必须和密码一致',
            'detail'=>'确认密码必须和密码一致',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    INCONSISTENT_NEW_PASSWORD=>
        array(
            'id'=>INCONSISTENT_NEW_PASSWORD,
            'link'=>'',
            'status'=>403,
            'code'=>'INCONSISTENT_PASSWORD',
            'title'=>'确认密码必须和新密码一致',
            'detail'=>'确认密码必须和新密码一致',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    STATUS_DISABLED=>
        array(
            'id'=>STATUS_DISABLED,
            'link'=>'',
            'status'=>403,
            'code'=>'STATUS_DISABLED',
            'title'=>'该账户已禁用',
            'detail'=>'该账户已禁用',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    NICK_NAME_FORMAT_ERROR=>
        array(
            'id'=>NICK_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'NICK_NAME_FORMAT_ERROR',
            'title'=>'昵称格式不正确',
            'detail'=>'请输入2-20位的昵称',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    BRIEF_INTRODUCTION_FORMAT_ERROR=>
        array(
            'id'=>BRIEF_INTRODUCTION_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'BRIEF_INTRODUCTION_FORMAT_ERROR',
            'title'=>'简介格式不正确',
            'detail'=>'简介最多可输入200个字',
            'source'=>array(
                'pointer'=>'attachments'
            ),
            'meta'=>array()
        ),
    UNIFIED_SOCIAL_CREDIT_CODE_FORMAT_ERROR=>
        array(
            'id'=>UNIFIED_SOCIAL_CREDIT_CODE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'UNIFIED_SOCIAL_CREDIT_CODE_FORMAT_ERROR',
            'title'=>'统一社会信用代码格式不正确',
            'detail'=>'统一社会信用代码格式不正确',
            'source'=>array(
                'pointer'=>'unifiedSocialCreditCode'
            ),
            'meta'=>array()
        ),
    ENTERPRISE_EXIST=>
        array(
            'id'=>ENTERPRISE_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'ENTERPRISE_EXIST',
            'title'=>'该企业已存在',
            'detail'=>'该企业已存在',
            'source'=>array(
                'pointer'=>'unifiedSocialCreditCode'
            ),
            'meta'=>array()
        ),
    CONTACTS_PPHONE_FORMAT_ERROR=>
        array(
            'id'=>CONTACTS_PPHONE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'CONTACTS_PPHONE_FORMAT_ERROR',
            'title'=>'联系人电话格式不正确',
            'detail'=>'联系人电话格式不正确',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    APPLICABLE_OBJECT_NOT_EXIST=>
        array(
            'id'=>APPLICABLE_OBJECT_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'APPLICABLE_OBJECT_NOT_EXIST',
            'title'=>'适用对象不存在',
            'detail'=>'适用对象不存在',
            'source'=>array(
                'pointer'=>'applicableObject'
            ),
            'meta'=>array()
        ),
    APPLICABLE_INDUSTRIES_NOT_EXIST=>
        array(
            'id'=>APPLICABLE_INDUSTRIES_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'APPLICABLE_INDUSTRIES_NOT_EXIST',
            'title'=>'适用行业不存在',
            'detail'=>'适用行业不存在',
            'source'=>array(
                'pointer'=>'applicableIndustries'
            ),
            'meta'=>array()
        ),
    LEVEL_NOT_EXIST=>
        array(
            'id'=>LEVEL_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'LEVEL_NOT_EXIST',
            'title'=>'政策级别不存在',
            'detail'=>'政策级别不存在',
            'source'=>array(
                'pointer'=>'level'
            ),
            'meta'=>array()
        ),
    CLASSIFY_NOT_EXIST=>
        array(
            'id'=>CLASSIFY_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'CLASSIFY_NOT_EXIST',
            'title'=>'政策分类不存在',
            'detail'=>'政策分类不存在',
            'source'=>array(
                'pointer'=>'classify'
            ),
            'meta'=>array()
        ),
    
    ADMISSIBLE_ADDRESS_FORMAT_ERROR=>
        array(
            'id'=>ADMISSIBLE_ADDRESS_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'ADMISSIBLE_ADDRESS_FORMAT_ERROR',
            'title'=>'受理地址格式不正确',
            'detail'=>'受理地址格式不正确',
            'source'=>array(
                'pointer'=>'admissibleAddress'
            ),
            'meta'=>array()
        ),
    DISPATCH_DEPARTMENT_NAME_FORMAT_ERROR=>
        array(
            'id'=>DISPATCH_DEPARTMENT_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DISPATCH_DEPARTMENT_NAME_FORMAT_ERROR',
            'title'=>'部门名称格式不正确',
            'detail'=>'请填写2-10位汉字的发文部门名称',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    DISPATCH_DEPARTMENT_REMARK_FORMAT_ERROR=>
        array(
            'id'=>DISPATCH_DEPARTMENT_REMARK_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'DISPATCH_DEPARTMENT_REMARK_FORMAT_ERROR',
            'title'=>'备注格式不正确',
            'detail'=>'备注不能超过200个字',
            'source'=>array(
                'pointer'=>'remark'
            ),
            'meta'=>array()
        ),
    DISPATCH_DEPARTMENT_NAME_EXIST=>
        array(
            'id'=>DISPATCH_DEPARTMENT_NAME_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'DISPATCH_DEPARTMENT_NAME_EXIST',
            'title'=>'发文部门名称已存在',
            'detail'=>'该部门名称已存在，请重新填写',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    LABEL_NAME_FORMAT_ERROR=>
        array(
            'id'=>LABEL_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'LABEL_NAME_FORMAT_ERROR',
            'title'=>'标签名称格式不正确',
            'detail'=>'标签名称为2-10位汉字，请重新填写',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    LABEL_CATEGORY_NOT_EXIST=>
        array(
            'id'=>LABEL_CATEGORY_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'LABEL_CATEGORY_NOT_EXIST',
            'title'=>'标签分类不存在',
            'detail'=>'标签分类不存在',
            'source'=>array(
                'pointer'=>'category'
            ),
            'meta'=>array()
        ),
    LABEL_REMARK_FORMAT_ERROR=>
        array(
            'id'=>LABEL_REMARK_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'LABEL_REMARK_FORMAT_ERROR',
            'title'=>'标签备注格式不正确',
            'detail'=>'备注不能超过200个字',
            'source'=>array(
                'pointer'=>'remark'
            ),
            'meta'=>array()
        ),
    LABEL_NAME_EXIST=>
        array(
            'id'=>LABEL_NAME_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'LABEL_NAME_EXIST',
            'title'=>'标签名称已存在',
            'detail'=>'该标签名称已存在，请重新填写',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    SERVICE_CATEGORY_NAME_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_CATEGORY_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_CATEGORY_NAME_FORMAT_ERROR',
            'title'=>'服务分类名称格式不正确',
            'detail'=>'服务分类名称为2-10的汉字',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    SERVICE_CATEGORY_QUALIFICATION_NAME_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_CATEGORY_QUALIFICATION_NAME_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_CATEGORY_QUALIFICATION_NAME_FORMAT_ERROR',
            'title'=>'服务分类资质认证名称格式不正确',
            'detail'=>'服务分类资质认证名称格式不正确',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    SERVICE_CATEGORY_IS_QUALIFICATION_NOT_EXIST=>
        array(
            'id'=>SERVICE_CATEGORY_IS_QUALIFICATION_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_CATEGORY_IS_QUALIFICATION_NOT_EXIST',
            'title'=>'是否需要资质认证分类不存在',
            'detail'=>'是否需要资质认证分类不存在',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    CATEGORY_IS_EXIST=>
        array(
            'id'=>CATEGORY_IS_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'CATEGORY_IS_EXIST',
            'title'=>'分类已存在',
            'detail'=>'该分类已存在，请重新填写',
            'source'=>array(
                'pointer'=>'name'
            ),
            'meta'=>array()
        ),
    SERVICE_REQUIREMENT_TITLE_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_REQUIREMENT_TITLE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_REQUIREMENT_TITLE_FORMAT_ERROR',
            'title'=>'需求标题格式不正确',
            'detail'=>'需求标题格式不正确，请重新填写',
            'source'=>array(
                'pointer'=>'title'
            ),
            'meta'=>array()
        ),
    MIN_PRICE_CAN_NOT_THAN_MAX_PRICE=>
        array(
            'id'=>MIN_PRICE_CAN_NOT_THAN_MAX_PRICE,
            'link'=>'',
            'status'=>403,
            'code'=>'MIN_PRICE_CAN_NOT_THAN_MAX_PRICE',
            'title'=>'最大价格不能低于最小价格',
            'detail'=>'最大价格不能低于最小价格',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    SERVICE_TITLE_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_TITLE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_TITLE_FORMAT_ERROR',
            'title'=>'服务标题格式不正确',
            'detail'=>'服务标题格式不正确，请重新填写',
            'source'=>array(
                'pointer'=>'title'
            ),
            'meta'=>array()
        ),
    SERVICE_OBJECT_NOT_EXIST=>
        array(
            'id'=>SERVICE_OBJECT_NOT_EXIST,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_OBJECT_NOT_EXIST',
            'title'=>'服务对象不存在',
            'detail'=>'服务对象不存在，请重新选择',
            'source'=>array(
                'pointer'=>'title'
            ),
            'meta'=>array()
        ),
    SERVICE_PRICE_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_PRICE_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_PRICE_FORMAT_ERROR',
            'title'=>'服务价格格式不正确',
            'detail'=>'服务价格格式不正确，请重新填写',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    SERVICE_CONTRACT_FORMAT_ERROR=>
        array(
            'id'=>SERVICE_CONTRACT_FORMAT_ERROR,
            'link'=>'',
            'status'=>403,
            'code'=>'SERVICE_CONTRACT_FORMAT_ERROR',
            'title'=>'服务合同格式不正确',
            'detail'=>'服务合同为pdf格式，请重新上传',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
    ENTERPRISE_NOT_AUTHENTICATION_SERVICE_CATEGORY=>
        array(
            'id'=>ENTERPRISE_NOT_AUTHENTICATION_SERVICE_CATEGORY,
            'link'=>'',
            'status'=>403,
            'code'=>'ENTERPRISE_NOT_AUTHENTICATION_SERVICE_CATEGORY',
            'title'=>'该企业未认证该分类',
            'detail'=>'该企业未认证该分类，请重新选择',
            'source'=>array(
                'pointer'=>''
            ),
            'meta'=>array()
        ),
);
